##
##
##
## $Id$
CMAKE_MINIMUM_REQUIRED(VERSION 2.4.5)

PROJECT(Name)

# Define self include path
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_SOURCE_DIR})
INCLUDE_DIRECTORIES(${CMAKE_CURRENT_BINARY_DIR})


ADD_LIBRARY($Name ${Name_lib_SRCS} ${Name_lib_HDRS})
SET_TARGET_PROPERTIES($Name PROPERTIES VERSION 0.0.0)


INSTALL(TARGETS $Name DESTINATION lib)
