/* automatically generated by CMake */
/* edit CMake script to change the values */
#define PHP_MAJOR_VERSION ${PHP_MAJOR_VERSION}
#define PHP_MINOR_VERSION ${PHP_MINOR_VERSION}
#define PHP_RELEASE_VERSION ${PHP_RELEASE_VERSION}
#define PHP_EXTRA_VERSION "${PHP_EXTRA_VERSION}"
#define PHP_VERSION "${PHP_VERSION}"
#define PHP_VERSION_ID ${PHP_VERSION_ID}
